export type PaletteMode = 'full' | 'free' | 'custom';

export type RGB = [number, number, number];
export type PaletteColor = { rgb: RGB; name: string; paid: boolean };

export const MASTER_COLORS: PaletteColor[] = [
  { rgb: [0, 0, 0], name: 'Black', paid: false },
  { rgb: [60, 60, 60], name: 'Dark Gray', paid: false },
  { rgb: [120, 120, 120], name: 'Gray', paid: false },
  { rgb: [170, 170, 170], name: 'Medium Gray', paid: true },
  { rgb: [210, 210, 210], name: 'Light Gray', paid: false },
  { rgb: [255, 255, 255], name: 'White', paid: false },
  { rgb: [96, 0, 24], name: 'Deep Red', paid: false },
  { rgb: [165, 14, 30], name: 'Dark Red', paid: true },
  { rgb: [237, 28, 36], name: 'Red', paid: false },
  { rgb: [250, 128, 114], name: 'Light Red', paid: true },
  { rgb: [228, 92, 26], name: 'Dark Orange', paid: true },
  { rgb: [255, 127, 39], name: 'Orange', paid: false },
  { rgb: [246, 170, 9], name: 'Gold', paid: false },
  { rgb: [249, 221, 59], name: 'Yellow', paid: false },
  { rgb: [255, 250, 188], name: 'Light Yellow', paid: false },
  { rgb: [156, 132, 49], name: 'Dark Goldenrod', paid: true },
  { rgb: [197, 173, 49], name: 'Goldenrod', paid: true },
  { rgb: [232, 212, 95], name: 'Light Goldenrod', paid: true },
  { rgb: [74, 107, 58], name: 'Dark Olive', paid: true },
  { rgb: [90, 148, 74], name: 'Olive', paid: true },
  { rgb: [132, 197, 115], name: 'Light Olive', paid: true },
  { rgb: [14, 185, 104], name: 'Dark Green', paid: false },
  { rgb: [19, 230, 123], name: 'Green', paid: false },
  { rgb: [135, 255, 94], name: 'Light Green', paid: false },
  { rgb: [12, 129, 110], name: 'Dark Teal', paid: false },
  { rgb: [16, 174, 166], name: 'Teal', paid: false },
  { rgb: [19, 225, 190], name: 'Light Teal', paid: false },
  { rgb: [15, 121, 159], name: 'Dark Cyan', paid: true },
  { rgb: [96, 247, 242], name: 'Cyan', paid: false },
  { rgb: [187, 250, 242], name: 'Light Cyan', paid: true },
  { rgb: [40, 80, 158], name: 'Dark Blue', paid: false },
  { rgb: [64, 147, 228], name: 'Blue', paid: false },
  { rgb: [125, 199, 255], name: 'Light Blue', paid: true },
  { rgb: [77, 49, 184], name: 'Dark Indigo', paid: true },
  { rgb: [107, 80, 246], name: 'Indigo', paid: false },
  { rgb: [153, 177, 251], name: 'Light Indigo', paid: false },
  { rgb: [74, 66, 132], name: 'Dark Slate Blue', paid: true },
  { rgb: [122, 113, 196], name: 'Slate Blue', paid: true },
  { rgb: [181, 174, 241], name: 'Light Slate Blue', paid: true },
  { rgb: [120, 12, 153], name: 'Dark Purple', paid: false },
  { rgb: [170, 56, 185], name: 'Purple', paid: false },
  { rgb: [224, 159, 249], name: 'Light Purple', paid: false },
  { rgb: [203, 0, 122], name: 'Dark Pink', paid: false },
  { rgb: [236, 31, 128], name: 'Pink', paid: false },
  { rgb: [243, 141, 169], name: 'Light Pink', paid: false },
  { rgb: [155, 82, 73], name: 'Dark Peach', paid: true },
  { rgb: [209, 128, 120], name: 'Peach', paid: true },
  { rgb: [250, 182, 164], name: 'Light Peach', paid: true },
  { rgb: [104, 70, 52], name: 'Dark Brown', paid: false },
  { rgb: [149, 104, 42], name: 'Brown', paid: false },
  { rgb: [219, 164, 99], name: 'Light Brown', paid: true },
  { rgb: [123, 99, 82], name: 'Dark Tan', paid: true },
  { rgb: [156, 132, 107], name: 'Tan', paid: true },
  { rgb: [214, 181, 148], name: 'Light Tan', paid: true },
  { rgb: [209, 128, 81], name: 'Dark Beige', paid: true },
  { rgb: [248, 178, 119], name: 'Beige', paid: false },
  { rgb: [255, 197, 165], name: 'Light Beige', paid: true },
  { rgb: [109, 100, 63], name: 'Dark Stone', paid: true },
  { rgb: [148, 140, 107], name: 'Stone', paid: true },
  { rgb: [205, 197, 158], name: 'Light Stone', paid: true },
  { rgb: [51, 57, 65], name: 'Dark Slate', paid: true },
  { rgb: [109, 117, 141], name: 'Slate', paid: true },
  { rgb: [179, 185, 209], name: 'Light Slate', paid: true },
];

export function getPalette(mode: PaletteMode): RGB[] {
  if (mode === 'free') return MASTER_COLORS.filter(c => !c.paid).map(c => c.rgb as RGB);
  
  return MASTER_COLORS.map(c => c.rgb as RGB);
}

export function quantizeCanvasToPalette(canvas: OffscreenCanvas, palette: RGB[]): OffscreenCanvas {
  const cx = canvas.getContext('2d', { willReadFrequently: true })!;
  const img = cx.getImageData(0, 0, canvas.width, canvas.height);
  const data = img.data;
  const pal = palette;
  for (let i = 0; i < data.length; i += 4) {
    const a = data[i + 3];
    if (a < 128) {
      data[i] = 0; data[i + 1] = 0; data[i + 2] = 0; data[i + 3] = 0; 
      continue;
    }
    
    let best = 0; let bestD = 1e12;
    const r = data[i], g = data[i + 1], b = data[i + 2];
    for (let p = 0; p < pal.length; p++) {
      const pr = pal[p][0], pg = pal[p][1], pb = pal[p][2];
      const dr = r - pr, dg = g - pg, db = b - pb;
      const d = dr * dr + dg * dg + db * db;
      if (d < bestD) { bestD = d; best = p; }
    }
    const c = pal[best];
    data[i] = c[0]; data[i + 1] = c[1]; data[i + 2] = c[2]; data[i + 3] = 255; 
  }
  cx.putImageData(img, 0, 0);
  return canvas;
}


export function getFreeIndices(): number[] {
  const arr: number[] = [];
  for (let i = 0; i < MASTER_COLORS.length; i++) if (!MASTER_COLORS[i].paid) arr.push(i);
  return arr;
}

export function getPaletteFromIndices(indices: number[]): RGB[] {
  const out: RGB[] = [];
  const seen = new Set<number>();
  for (const idx of indices || []) {
    if (idx == null) continue;
    const i = Math.max(0, Math.min(MASTER_COLORS.length - 1, idx | 0));
    if (seen.has(i)) continue;
    seen.add(i);
    out.push(MASTER_COLORS[i].rgb as RGB);
  }
  return out.length ? out : getPalette('free');
}

export type PalettePreset = { id: string; name: string; indices: number[]; tags?: string[] };

function indicesByNames(names: string[]): number[] {
  try {
    const seen = new Set<number>();
    const res: number[] = [];
    for (const n of names) {
      const i = MASTER_COLORS.findIndex(c => c.name === n);
      if (i >= 0 && !seen.has(i)) { seen.add(i); res.push(i); }
    }
    return res.sort((a,b)=>a-b);
  } catch {
    return [];
  }
}

export const PALETTE_PRESETS: PalettePreset[] = [
  { id: 'grayscale_basic', name: 'Grayscale (Basic)', indices: indicesByNames(['Black','Dark Gray','Gray','Light Gray','White']), tags: ['mono','neutral'] },
  { id: 'grayscale_extended', name: 'Grayscale (Extended)', indices: indicesByNames(['Black','Dark Gray','Gray','Medium Gray','Light Gray','White']), tags: ['mono','neutral','paid'] },
  { id: 'fire', name: 'Fire', indices: indicesByNames(['Deep Red','Dark Red','Red','Dark Orange','Orange','Gold','Yellow','Light Yellow']), tags: ['warm'] },
  { id: 'sunset', name: 'Sunset', indices: indicesByNames(['Dark Red','Red','Orange','Gold','Yellow','Light Yellow','Purple','Indigo']), tags: ['warm'] },
  { id: 'sunrise', name: 'Sunrise', indices: indicesByNames(['Red','Light Red','Orange','Gold','Yellow','Light Yellow']), tags: ['warm'] },
  { id: 'autumn', name: 'Autumn', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Brown','Dark Brown','Beige','Dark Beige','Tan']), tags: ['earth'] },
  { id: 'earth', name: 'Earth', indices: indicesByNames(['Dark Brown','Brown','Light Brown','Dark Tan','Tan','Light Tan','Dark Stone','Stone','Light Stone']), tags: ['earth','neutral'] },
  { id: 'desert', name: 'Desert', indices: indicesByNames(['Dark Beige','Beige','Light Beige','Brown','Light Brown','Gold','Goldenrod','Light Goldenrod']), tags: ['earth','warm'] },
  { id: 'skin', name: 'Skin tones', indices: indicesByNames(['Dark Peach','Peach','Light Peach','Tan','Light Tan','Beige','Light Beige','Brown']), tags: ['portrait','paid'] },
  { id: 'forest', name: 'Forest', indices: indicesByNames(['Dark Olive','Olive','Light Olive','Dark Green','Green','Light Green','Dark Teal','Teal']), tags: ['nature','green','paid'] },
  { id: 'spring', name: 'Spring Pastels', indices: indicesByNames(['Light Pink','Light Purple','Light Indigo','Light Blue','Light Teal','Light Green','Light Yellow']), tags: ['pastel'] },
  { id: 'summer', name: 'Summer', indices: indicesByNames(['Red','Orange','Yellow','Green','Blue','Cyan','White']), tags: ['season'] },
  { id: 'winter', name: 'Winter', indices: indicesByNames(['Dark Blue','Blue','Light Blue','Dark Slate','Slate','Light Slate','Light Cyan','White']), tags: ['season','cool','paid'] },
  { id: 'ocean', name: 'Ocean', indices: indicesByNames(['Dark Cyan','Cyan','Light Cyan','Dark Blue','Blue','Light Blue','Teal','Light Teal']), tags: ['cool','water','paid'] },
  { id: 'sky', name: 'Sky', indices: indicesByNames(['Light Blue','Blue','Light Cyan','White','Light Slate Blue']), tags: ['cool'] },
  { id: 'ice', name: 'Ice', indices: indicesByNames(['Light Blue','Light Cyan','White','Light Slate','Light Indigo']), tags: ['cool','pastel','paid'] },
  { id: 'lavender', name: 'Lavender', indices: indicesByNames(['Light Purple','Purple','Light Indigo','Indigo','Slate Blue']), tags: ['purple','cool'] },
  { id: 'purple_dream', name: 'Purple Dream', indices: indicesByNames(['Dark Purple','Purple','Light Purple','Indigo','Light Indigo','Pink']), tags: ['purple'] },
  { id: 'pink_candy', name: 'Pink Candy', indices: indicesByNames(['Light Pink','Pink','Light Purple','Light Blue','Light Yellow','White']), tags: ['pastel','bright'] },
  { id: 'berry', name: 'Berry', indices: indicesByNames(['Dark Pink','Pink','Light Pink','Purple','Light Purple','Red','Light Red']), tags: ['warm'] },
  { id: 'retro', name: 'Retro', indices: indicesByNames(['Brown','Beige','Light Beige','Goldenrod','Light Goldenrod','Slate','Light Slate']), tags: ['vintage'] },
  { id: 'vintage', name: 'Vintage', indices: indicesByNames(['Dark Brown','Brown','Tan','Beige','Goldenrod','Slate Blue','Light Slate Blue']), tags: ['vintage'] },
  { id: 'neon', name: 'Neon Core', indices: indicesByNames(['Black','White','Red','Green','Blue','Cyan','Yellow','Pink']), tags: ['bright'] },
  { id: 'vaporwave', name: 'Vaporwave', indices: indicesByNames(['Pink','Light Pink','Purple','Light Purple','Light Blue','Cyan','Indigo']), tags: ['aesthetic','pastel'] },
  { id: 'royal', name: 'Royal', indices: indicesByNames(['Purple','Indigo','Light Indigo','Slate Blue','Light Slate Blue','Gold','White']), tags: ['luxury'] },
  { id: 'steel', name: 'Steel', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Slate Blue','Slate Blue','Light Slate Blue','Gray','Light Gray']), tags: ['cool','neutral'] },
  { id: 'stone', name: 'Stone Cold', indices: indicesByNames(['Dark Stone','Stone','Light Stone','Dark Slate','Slate','Light Slate','Light Gray','White']), tags: ['neutral'] },
  { id: 'mono_red', name: 'Monochrome Red', indices: indicesByNames(['Black','Deep Red','Dark Red','Red','Light Red','White']), tags: ['mono'] },
  { id: 'mono_green', name: 'Monochrome Green', indices: indicesByNames(['Black','Dark Green','Green','Light Green','White']), tags: ['mono'] },
  { id: 'mono_blue', name: 'Monochrome Blue', indices: indicesByNames(['Black','Dark Blue','Blue','Light Blue','White']), tags: ['mono'] },
  { id: 'mono_purple', name: 'Monochrome Purple', indices: indicesByNames(['Black','Dark Purple','Purple','Light Purple','White']), tags: ['mono'] },
  { id: 'teal_cyan', name: 'Teal–Cyan', indices: indicesByNames(['Black','Dark Teal','Teal','Light Teal','Cyan','Light Cyan','White']), tags: ['cool','mono','paid'] },
  { id: 'gold_brown', name: 'Gold & Brown', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Dark Brown','Brown','Light Brown','Beige','Light Beige']), tags: ['earth','warm'] },
  { id: 'coffee', name: 'Coffee', indices: indicesByNames(['Dark Brown','Brown','Dark Beige','Beige','Light Beige','Tan','Light Tan']), tags: ['earth'] },
  { id: 'sand', name: 'Sand', indices: indicesByNames(['Beige','Light Beige','Tan','Light Tan','Light Yellow','White']), tags: ['earth','pastel'] },
  { id: 'olive_mil', name: 'Olive Military', indices: indicesByNames(['Black','Dark Olive','Olive','Light Olive','Dark Slate','Slate','Light Slate']), tags: ['green','paid'] },
  { id: 'rainbow7', name: 'Rainbow 7', indices: indicesByNames(['Red','Orange','Yellow','Green','Blue','Indigo','Purple','White']), tags: ['bright'] },
  { id: 'gb_like', name: 'GB-like', indices: indicesByNames(['Dark Olive','Olive','Light Olive','Light Beige']), tags: ['retro','paid'] },
  { id: 'chocolate', name: 'Chocolate', indices: indicesByNames(['Dark Brown','Brown','Light Brown','Beige','Light Beige']), tags: ['earth'] },
  { id: 'slate_blue', name: 'Slate Blue Scheme', indices: indicesByNames(['Dark Slate Blue','Slate Blue','Light Slate Blue','Indigo','Light Indigo','White']), tags: ['cool'] },
  { id: 'coral_reef', name: 'Coral Reef', indices: indicesByNames(['Pink','Light Pink','Peach','Light Peach','Teal','Light Teal','Cyan','Light Cyan','Light Blue']), tags: ['pastel','sea','paid'] },
  { id: 'mint', name: 'Mint', indices: indicesByNames(['Light Green','Light Teal','Light Cyan','White','Light Yellow']), tags: ['pastel','cool'] },
  { id: 'fire_ice', name: 'Fire & Ice', indices: indicesByNames(['Red','Orange','Gold','Dark Blue','Blue','Light Blue','Cyan','White']), tags: ['contrast'] },
  { id: 'noir_accent', name: 'Noir Accent', indices: indicesByNames(['Black','Gray','White','Red','Gold']), tags: ['minimal'] },
  { id: 'duo_red_cyan', name: 'Duo Red–Cyan', indices: indicesByNames(['Black','Red','Light Red','Cyan','Light Cyan','White']), tags: ['duo','contrast','bright'] },
  { id: 'duo_blue_orange', name: 'Duo Blue–Orange', indices: indicesByNames(['Black','Dark Blue','Blue','Dark Orange','Orange','White']), tags: ['duo','contrast','warm','cool'] },
  { id: 'duo_purple_yellow', name: 'Duo Purple–Yellow', indices: indicesByNames(['Black','Purple','Light Purple','Yellow','Light Yellow','White']), tags: ['duo','contrast'] },
  { id: 'duo_green_pink', name: 'Duo Green–Pink', indices: indicesByNames(['Black','Dark Green','Green','Light Green','Pink','Light Pink','White']), tags: ['duo','contrast','pastel'] },
  { id: 'triad_rgb', name: 'Triad RGB', indices: indicesByNames(['Black','Red','Green','Blue','White']), tags: ['triad','classic','bright'] },
  { id: 'triad_cmy', name: 'Triad CMY', indices: indicesByNames(['Black','Cyan','Yellow','Pink','White']), tags: ['triad','bright'] },
  { id: 'triad_orange_teal_purple', name: 'Triad Orange–Teal–Purple', indices: indicesByNames(['Black','Orange','Teal','Purple','White']), tags: ['triad','contrast','aesthetic'] },
  { id: 'pastel_sunset2', name: 'Pastel Sunset', indices: indicesByNames(['Light Pink','Light Peach','Light Yellow','Light Purple','Light Indigo','Light Blue','White']), tags: ['pastel','warm'] },
  { id: 'pastel_ocean', name: 'Pastel Ocean', indices: indicesByNames(['Light Teal','Light Cyan','Light Blue','Light Indigo','White']), tags: ['pastel','sea','cool'] },
  { id: 'pastel_forest', name: 'Pastel Forest', indices: indicesByNames(['Light Olive','Light Green','Light Teal','Light Yellow','Light Beige','White']), tags: ['pastel','nature'] },
  { id: 'pastel_candy', name: 'Pastel Candy', indices: indicesByNames(['Light Pink','Light Purple','Light Blue','Light Yellow','White']), tags: ['pastel','bright'] },
  { id: 'fruit_strawberry', name: 'Strawberry', indices: indicesByNames(['Red','Light Red','Pink','Light Pink','Green','Light Green','White']), tags: ['bright'] },
  { id: 'fruit_watermelon', name: 'Watermelon', indices: indicesByNames(['Dark Green','Green','Light Green','Pink','Light Pink','White']), tags: ['bright','summer'] },
  { id: 'fruit_mango', name: 'Mango', indices: indicesByNames(['Dark Orange','Orange','Gold','Light Yellow','White']), tags: ['warm'] },
  { id: 'fruit_blueberry', name: 'Blueberry', indices: indicesByNames(['Dark Indigo','Indigo','Light Indigo','Light Blue','White']), tags: ['cool'] },
  { id: 'sky_dawn', name: 'Dawn', indices: indicesByNames(['Pink','Light Pink','Light Purple','Light Indigo','Light Blue','Light Yellow','White']), tags: ['sky','pastel'] },
  { id: 'sky_noon', name: 'Noon Sky', indices: indicesByNames(['Light Blue','Blue','Light Cyan','White','Yellow']), tags: ['sky','bright'] },
  { id: 'sky_dusk', name: 'Dusk', indices: indicesByNames(['Indigo','Dark Indigo','Purple','Pink','Orange','Gold']), tags: ['sky','warm','cool'] },
  { id: 'sky_night', name: 'Night Sky', indices: indicesByNames(['Black','Dark Blue','Blue','Light Indigo','Light Yellow','White']), tags: ['sky','cool','neutral'] },
  { id: 'sea_tropical', name: 'Tropical Sea', indices: indicesByNames(['Teal','Light Teal','Cyan','Light Cyan','Light Yellow','White']), tags: ['sea','cool','bright'] },
  { id: 'sea_deep', name: 'Deep Sea', indices: indicesByNames(['Dark Blue','Blue','Dark Teal','Dark Cyan','Slate','Light Slate']), tags: ['sea','cool','paid'] },
  { id: 'coral_coast', name: 'Coral Coast', indices: indicesByNames(['Pink','Light Pink','Orange','Gold','Teal','Light Teal','Cyan']), tags: ['sea','pastel'] },
  { id: 'polar', name: 'Polar', indices: indicesByNames(['Light Cyan','Light Blue','White','Slate','Light Slate']), tags: ['cool','ice'] },
  { id: 'lava', name: 'Lava', indices: indicesByNames(['Deep Red','Dark Red','Red','Dark Orange','Orange','Gold','Black']), tags: ['warm','contrast'] },
  { id: 'forest_moss', name: 'Forest Moss', indices: indicesByNames(['Dark Olive','Olive','Light Olive','Dark Green','Green','Light Green','Light Beige']), tags: ['nature','green'] },
  { id: 'sandstone', name: 'Sandstone', indices: indicesByNames(['Dark Beige','Beige','Light Beige','Tan','Light Tan','Light Yellow']), tags: ['earth','warm'] },
  { id: 'sepia_print', name: 'Sepia Print', indices: indicesByNames(['Dark Brown','Brown','Light Brown','Tan','Beige','Light Beige','Light Yellow']), tags: ['vintage','earth'] },
  { id: 'ash_steel', name: 'Ash & Steel', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Gray','Gray','Light Gray','White']), tags: ['neutral','cool'] },
  { id: 'noir_cyan', name: 'Noir Cyan', indices: indicesByNames(['Black','Gray','White','Cyan','Light Cyan']), tags: ['minimal','noir'] },
  { id: 'noir_pink', name: 'Noir Pink', indices: indicesByNames(['Black','Gray','White','Pink','Light Pink']), tags: ['minimal','noir'] },
  { id: 'noir_gold', name: 'Noir Gold', indices: indicesByNames(['Black','Gray','White','Gold','Light Yellow']), tags: ['minimal','noir'] },
  { id: 'mono_orange', name: 'Monochrome Orange', indices: indicesByNames(['Black','Dark Orange','Orange','Gold','White']), tags: ['mono','warm'] },
  { id: 'mono_cyan2', name: 'Monochrome Cyan', indices: indicesByNames(['Black','Dark Cyan','Cyan','Light Cyan','White']), tags: ['mono','cool'] },
  { id: 'mono_pink', name: 'Monochrome Pink', indices: indicesByNames(['Black','Dark Pink','Pink','Light Pink','White']), tags: ['mono'] },
  { id: 'mono_brown', name: 'Monochrome Brown', indices: indicesByNames(['Black','Dark Brown','Brown','Light Brown','White']), tags: ['mono','earth'] },
  { id: 'retro_cga', name: 'Retro CGA', indices: indicesByNames(['Black','Cyan','Pink','White']), tags: ['retro','bright'] },
  { id: 'retro_cga_warm', name: 'Retro CGA Warm', indices: indicesByNames(['Black','Orange','Light Yellow','Pink','White']), tags: ['retro','bright','warm'] },
  { id: 'retro_gb_soft', name: 'GB Soft', indices: indicesByNames(['Dark Olive','Olive','Light Olive','Light Beige','White']), tags: ['retro'] },
  { id: 'icy_neon', name: 'Icy Neon', indices: indicesByNames(['Cyan','Light Cyan','Light Blue','Light Indigo','Pink']), tags: ['bright','pastel'] },
  { id: 'royal_alt', name: 'Royal Alt', indices: indicesByNames(['Indigo','Slate Blue','Light Slate Blue','Gold','White']), tags: ['luxury'] },
  { id: 'coffee_cream', name: 'Coffee & Cream', indices: indicesByNames(['Dark Brown','Brown','Beige','Light Beige','White']), tags: ['earth'] },
  { id: 'teal_orange_cinema', name: 'Teal & Orange (Cinema)', indices: indicesByNames(['Teal','Light Teal','Orange','Gold','Black','White']), tags: ['contrast','cinema'] },
  { id: 'aurora', name: 'Aurora', indices: indicesByNames(['Dark Blue','Indigo','Purple','Light Purple','Cyan','Light Cyan']), tags: ['cool','night'] },
  { id: 'cyberpunk', name: 'Cyberpunk', indices: indicesByNames(['Black','Indigo','Purple','Pink','Cyan','Light Cyan']), tags: ['aesthetic','bright'] },
  { id: 'cold_desat', name: 'Cold Desaturated', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Light Blue','Light Cyan','White']), tags: ['cool','neutral'] },
  { id: 'rust', name: 'Rust', indices: indicesByNames(['Dark Red','Dark Orange','Goldenrod','Brown','Dark Brown','Beige']), tags: ['earth','vintage','paid'] },
  { id: 'pumpkin_spice', name: 'Pumpkin Spice', indices: indicesByNames(['Dark Orange','Orange','Gold','Brown','Light Brown','Beige']), tags: ['season','autumn'] },
  { id: 'spring_meadow', name: 'Spring Meadow', indices: indicesByNames(['Light Green','Green','Light Olive','Light Yellow','Light Beige','White']), tags: ['season','spring','pastel'] },
  { id: 'winter_holiday', name: 'Winter Holiday', indices: indicesByNames(['Red','Green','White','Gold','Dark Green']), tags: ['season','winter','contrast'] },
  { id: 'storm', name: 'Storm', indices: indicesByNames(['Dark Blue','Slate','Dark Slate','Gray','Light Gray','White']), tags: ['sky','neutral','cool','paid'] },
  { id: 'sunny_fields', name: 'Sunny Fields', indices: indicesByNames(['Green','Light Green','Yellow','Light Yellow','Light Blue','White']), tags: ['nature','bright'] },
  { id: 'emerald_sea', name: 'Emerald Sea', indices: indicesByNames(['Dark Teal','Teal','Light Teal','Cyan','Light Cyan','White']), tags: ['sea','cool'] },
  { id: 'violet_dreams', name: 'Violet Dreams', indices: indicesByNames(['Dark Purple','Purple','Light Purple','Indigo','Light Indigo','White']), tags: ['purple','cool'] },
  { id: 'nord', name: 'Nord', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Blue','Blue','Light Cyan','White']), tags: ['cool','neutral','nord'] },
  { id: 'solarized_dark', name: 'Solarized Dark', indices: indicesByNames(['Dark Brown','Brown','Dark Tan','Dark Orange','Goldenrod','Teal','Cyan']), tags: ['earth','retro'] },
  { id: 'solarized_light', name: 'Solarized Light', indices: indicesByNames(['Beige','Light Beige','Light Tan','Goldenrod','Light Goldenrod','Light Cyan','Light Blue']), tags: ['earth','pastel'] },
  { id: 'miami_nights', name: 'Miami Nights', indices: indicesByNames(['Indigo','Purple','Pink','Light Pink','Cyan']), tags: ['aesthetic','neon','night'] },
  { id: 'sakura', name: 'Sakura', indices: indicesByNames(['Pink','Light Pink','Light Purple','Light Indigo','White']), tags: ['pastel','spring'] },
  { id: 'toxic', name: 'Toxic', indices: indicesByNames(['Black','Dark Green','Green','Light Green','Yellow','Light Yellow']), tags: ['neon','contrast'] },
  { id: 'steampunk', name: 'Steampunk', indices: indicesByNames(['Dark Brown','Brown','Dark Beige','Beige','Gold']), tags: ['vintage','earth'] },
  { id: 'peachy', name: 'Peachy', indices: indicesByNames(['Dark Peach','Peach','Light Peach','Light Yellow','White']), tags: ['pastel','warm'] },
  { id: 'forest_night', name: 'Forest Night', indices: indicesByNames(['Black','Dark Olive','Olive','Dark Green','Dark Teal']), tags: ['nature','dark'] },
  { id: 'slate_teal', name: 'Slate Teal', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Teal','Teal','Light Teal']), tags: ['cool','neutral'] },
  { id: 'dawn_beach', name: 'Dawn Beach', indices: indicesByNames(['Light Pink','Light Peach','Light Yellow','Light Beige','White']), tags: ['pastel','beach','warm'] },
  { id: 'firefly', name: 'Firefly', indices: indicesByNames(['Black','Dark Blue','Indigo','Gold','Light Yellow']), tags: ['night','contrast'] },
  { id: 'copper_turquoise', name: 'Copper & Turquoise', indices: indicesByNames(['Dark Brown','Brown','Gold','Teal','Light Teal','Cyan']), tags: ['contrast','aesthetic'] },
  { id: 'mossy_stone', name: 'Mossy Stone', indices: indicesByNames(['Dark Stone','Stone','Light Stone','Dark Olive','Olive','Light Olive']), tags: ['earth','nature','neutral'] },
  { id: 'berry_sorbet', name: 'Berry Sorbet', indices: indicesByNames(['Dark Pink','Pink','Light Pink','Light Purple','Light Blue']), tags: ['pastel','bright'] },
  { id: 'glacier', name: 'Glacier', indices: indicesByNames(['Light Cyan','Light Blue','Light Indigo','White','Slate']), tags: ['cool','ice','pastel'] },
  { id: 'evening_city', name: 'Evening City', indices: indicesByNames(['Dark Blue','Blue','Light Indigo','Gold','Light Yellow','White']), tags: ['city','night','contrast'] },
  { id: 'sunbleached', name: 'Sunbleached', indices: indicesByNames(['Light Beige','Light Yellow','Light Tan','Light Stone','White']), tags: ['pastel','beach','warm'] },
  { id: 'jade_gold', name: 'Jade & Gold', indices: indicesByNames(['Dark Teal','Teal','Light Teal','Gold','Light Goldenrod','White']), tags: ['contrast','aesthetic'] },
  { id: 'amber_forest', name: 'Amber Forest', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Dark Green','Green','Light Green']), tags: ['nature','warm'] },
  { id: 'midnight_lights', name: 'Midnight Lights', indices: indicesByNames(['Black','Dark Blue','Indigo','Light Indigo','Gold','White']), tags: ['night','contrast'] },
  { id: 'arctic_night', name: 'Arctic Night', indices: indicesByNames(['Black','Dark Blue','Light Cyan','Slate','White']), tags: ['night','ice','cool'] },
  { id: 'dune', name: 'Dune', indices: indicesByNames(['Dark Beige','Beige','Light Beige','Gold','Light Yellow','Tan']), tags: ['desert','earth','warm'] },
  { id: 'sahara_sunset', name: 'Sahara Sunset', indices: indicesByNames(['Dark Orange','Orange','Gold','Light Yellow','Light Beige','Pink']), tags: ['desert','sunset','warm'] },
  { id: 'oasis', name: 'Oasis', indices: indicesByNames(['Beige','Light Beige','Light Yellow','Teal','Light Teal','Cyan','Light Cyan']), tags: ['desert','sea','cool'] },
  { id: 'reef_shallows', name: 'Reef Shallows', indices: indicesByNames(['Light Teal','Light Cyan','Light Blue','Light Yellow','White']), tags: ['sea','pastel'] },
  { id: 'abyss', name: 'Abyss', indices: indicesByNames(['Black','Dark Blue','Dark Teal','Dark Cyan','Slate']), tags: ['sea','night','cool'] },
  { id: 'lagoon', name: 'Lagoon', indices: indicesByNames(['Teal','Light Teal','Cyan','Light Cyan','Light Blue','White']), tags: ['sea','cool','bright'] },
  { id: 'storm_sea', name: 'Storm Sea', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Blue','Blue','Light Cyan']), tags: ['sea','cool','neutral'] },
  { id: 'overcast', name: 'Overcast', indices: indicesByNames(['Light Slate','Slate','Light Gray','White','Light Blue']), tags: ['sky','neutral','cool'] },
  { id: 'thunderstorm', name: 'Thunderstorm', indices: indicesByNames(['Dark Slate','Dark Blue','Indigo','Light Yellow','White']), tags: ['sky','night','contrast'] },
  { id: 'ember', name: 'Ember', indices: indicesByNames(['Black','Deep Red','Dark Red','Red','Dark Orange','Gold']), tags: ['fire','warm','contrast'] },
  { id: 'forge', name: 'Forge', indices: indicesByNames(['Dark Brown','Brown','Dark Orange','Orange','Gold']), tags: ['fire','earth','warm'] },
  { id: 'sunflare', name: 'Sunflare', indices: indicesByNames(['Orange','Gold','Yellow','Light Yellow','White']), tags: ['warm','bright'] },
  { id: 'icicle', name: 'Icicle', indices: indicesByNames(['Light Blue','Light Cyan','White','Light Slate']), tags: ['ice','cool','pastel'] },
  { id: 'winter_moon', name: 'Winter Moon', indices: indicesByNames(['Dark Blue','Light Indigo','Light Cyan','White']), tags: ['night','ice','cool'] },
  { id: 'forest_conifer', name: 'Forest Conifer', indices: indicesByNames(['Dark Green','Green','Light Green','Dark Olive','Olive','Light Olive']), tags: ['forest','nature'] },
  { id: 'mangrove', name: 'Mangrove', indices: indicesByNames(['Dark Teal','Teal','Light Teal','Dark Green','Green']), tags: ['forest','sea','cool'] },
  { id: 'metro', name: 'Metro', indices: indicesByNames(['Black','Slate','Light Slate','Indigo','Light Indigo']), tags: ['city','cool'] },
  { id: 'industrial', name: 'Industrial', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Gray','Gray','Light Gray']), tags: ['city','neutral'] },
  { id: 'noir_blood', name: 'Noir Blood', indices: indicesByNames(['Black','Gray','White','Dark Red','Red']), tags: ['noir','contrast'] },
  { id: 'noir_emerald', name: 'Noir Emerald', indices: indicesByNames(['Black','Gray','White','Dark Green','Light Green']), tags: ['noir','contrast'] },
  { id: 'noir_sapphire', name: 'Noir Sapphire', indices: indicesByNames(['Black','Gray','White','Dark Blue','Light Blue']), tags: ['noir','contrast'] },
  { id: 'citrus', name: 'Citrus', indices: indicesByNames(['Dark Orange','Orange','Gold','Yellow','Light Yellow','White']), tags: ['fruit','warm','bright'] },
  { id: 'banana', name: 'Banana', indices: indicesByNames(['Gold','Yellow','Light Yellow','Light Beige','White']), tags: ['fruit','warm','pastel'] },
  { id: 'grape', name: 'Grape', indices: indicesByNames(['Dark Purple','Purple','Light Purple','Indigo','White']), tags: ['fruit','purple'] },
  { id: 'rose_garden', name: 'Rose Garden', indices: indicesByNames(['Dark Pink','Pink','Light Pink','Red','Light Red','White']), tags: ['warm','pastel'] },
  { id: 'lavender_field', name: 'Lavender Field', indices: indicesByNames(['Light Purple','Purple','Light Indigo','Light Blue','White']), tags: ['pastel','cool','purple'] },
  { id: 'analog_teal_cyan_blue', name: 'Analog Teal–Cyan–Blue', indices: indicesByNames(['Dark Teal','Teal','Cyan','Blue','Light Blue']), tags: ['analogous','cool'] },
  { id: 'analog_red_orange_gold', name: 'Analog Red–Orange–Gold', indices: indicesByNames(['Dark Red','Red','Dark Orange','Orange','Gold']), tags: ['analogous','warm'] },
  { id: 'analog_purple_pink_indigo', name: 'Analog Purple–Pink–Indigo', indices: indicesByNames(['Dark Purple','Purple','Pink','Light Pink','Indigo']), tags: ['analogous','aesthetic'] },
  { id: 'analog_green_olive_teal', name: 'Analog Green–Olive–Teal', indices: indicesByNames(['Dark Green','Green','Light Green','Olive','Teal']), tags: ['analogous','nature'] },
  { id: 'duo_blue_gold', name: 'Duo Blue–Gold', indices: indicesByNames(['Black','Blue','Light Blue','Gold','White']), tags: ['duo','contrast'] },
  { id: 'duo_purple_gold2', name: 'Duo Purple–Gold', indices: indicesByNames(['Black','Purple','Light Purple','Gold','White']), tags: ['duo','contrast','luxury'] },
  { id: 'duo_olive_pink', name: 'Duo Olive–Pink', indices: indicesByNames(['Black','Olive','Light Olive','Pink','Light Pink','White']), tags: ['duo','aesthetic'] },
  { id: 'duo_brown_cyan', name: 'Duo Brown–Cyan', indices: indicesByNames(['Black','Brown','Light Brown','Cyan','Light Cyan','White']), tags: ['duo','contrast'] },
  { id: 'duo_indigo_yellow', name: 'Duo Indigo–Yellow', indices: indicesByNames(['Black','Indigo','Light Indigo','Yellow','Light Yellow','White']), tags: ['duo','contrast'] },
  { id: 'triad_red_green_blue_soft', name: 'Triad RGB Soft', indices: indicesByNames(['Light Red','Light Green','Light Blue','White','Gray']), tags: ['triad','pastel'] },
  { id: 'triad_orange_teal_purple_soft', name: 'Triad OTP Soft', indices: indicesByNames(['Orange','Teal','Light Teal','Light Purple','White']), tags: ['triad','pastel','aesthetic'] },
  { id: 'royal_jewel', name: 'Royal Jewel', indices: indicesByNames(['Dark Purple','Purple','Indigo','Gold','White']), tags: ['luxury','cool','contrast'] },
  { id: 'autumn_forest', name: 'Autumn Forest', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Dark Olive','Olive','Brown']), tags: ['season','autumn','earth'] },
  { id: 'spring_blossom', name: 'Spring Blossom', indices: indicesByNames(['Light Pink','Light Purple','Light Green','Light Yellow','White']), tags: ['season','spring','pastel'] },
  { id: 'summer_breeze', name: 'Summer Breeze', indices: indicesByNames(['Light Blue','Cyan','Light Cyan','Light Teal','White']), tags: ['season','summer','cool'] },
  { id: 'harvest', name: 'Harvest', indices: indicesByNames(['Dark Orange','Orange','Gold','Beige','Light Beige','Brown']), tags: ['earth','warm','season'] },
  { id: 'basalt', name: 'Basalt', indices: indicesByNames(['Black','Dark Slate','Slate','Dark Stone','Stone','Light Stone']), tags: ['earth','neutral'] },
  { id: 'limestone', name: 'Limestone', indices: indicesByNames(['Stone','Light Stone','Light Gray','White','Beige']), tags: ['earth','neutral'] },
  { id: 'terracotta', name: 'Terracotta', indices: indicesByNames(['Dark Brown','Brown','Light Brown','Dark Orange','Orange','Beige']), tags: ['earth','warm'] },
  { id: 'rusty_steel', name: 'Rusty Steel', indices: indicesByNames(['Dark Red','Dark Orange','Goldenrod','Slate','Light Slate','Gray']), tags: ['vintage','neutral'] },
  { id: 'teal_orange_soft', name: 'Teal & Orange Soft', indices: indicesByNames(['Teal','Light Teal','Orange','Light Yellow','White']), tags: ['cinema','warm','cool'] },
  { id: 'cinema_cold', name: 'Cinema Cold', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Light Blue','Light Cyan']), tags: ['cinema','cool','neutral'] },
  { id: 'cinema_warm', name: 'Cinema Warm', indices: indicesByNames(['Dark Orange','Orange','Gold','Light Yellow','Beige']), tags: ['cinema','warm'] },
  { id: 'neon_mint', name: 'Neon Mint', indices: indicesByNames(['Black','Teal','Light Teal','Light Cyan','White']), tags: ['neon','bright','cool'] },
  { id: 'neon_magenta_cyan', name: 'Neon Magenta & Cyan', indices: indicesByNames(['Black','Dark Pink','Pink','Cyan','Light Cyan','White']), tags: ['neon','bright','aesthetic'] },
  { id: 'neon_sunset', name: 'Neon Sunset', indices: indicesByNames(['Black','Purple','Pink','Orange','Light Yellow','White']), tags: ['neon','night','aesthetic'] },
  { id: 'city_park', name: 'City Park', indices: indicesByNames(['Slate','Light Slate','Green','Light Green','Light Yellow']), tags: ['city','nature'] },
  { id: 'old_photo', name: 'Old Photo', indices: indicesByNames(['Dark Brown','Brown','Tan','Beige','Light Beige','Light Yellow']), tags: ['vintage','earth'] },
  { id: 'coffee_rush', name: 'Coffee Rush', indices: indicesByNames(['Dark Brown','Brown','Light Brown','Dark Beige','Beige','Light Beige']), tags: ['earth','warm'] },
  { id: 'copper_rust', name: 'Copper Rust', indices: indicesByNames(['Dark Brown','Brown','Dark Orange','Goldenrod','Beige']), tags: ['earth','vintage'] },
  { id: 'ice_cave', name: 'Ice Cave', indices: indicesByNames(['Dark Blue','Light Blue','Light Cyan','White','Light Slate']), tags: ['ice','cool'] },
  { id: 'frozen_forest', name: 'Frozen Forest', indices: indicesByNames(['Dark Green','Green','Light Green','Light Blue','Light Cyan','White']), tags: ['ice','nature','cool'] },
  { id: 'candlelight', name: 'Candlelight', indices: indicesByNames(['Black','Dark Brown','Brown','Gold','Light Yellow','White']), tags: ['night','warm'] },
  { id: 'pearl', name: 'Pearl', indices: indicesByNames(['White','Light Gray','Light Beige','Light Blue','Light Cyan']), tags: ['pastel','neutral'] },
  { id: 'chalkboard', name: 'Chalkboard', indices: indicesByNames(['Black','Dark Gray','Gray','Light Gray','White','Light Blue']), tags: ['neutral','city'] },
  { id: 'teal_slate', name: 'Teal Slate', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Teal','Light Teal']), tags: ['cool','neutral'] },
  { id: 'golden_slate', name: 'Golden Slate', indices: indicesByNames(['Dark Slate','Slate','Gold','Light Yellow','White']), tags: ['contrast','neutral'] },
  { id: 'sand_and_sea', name: 'Sand & Sea', indices: indicesByNames(['Beige','Light Beige','Light Yellow','Light Blue','Light Cyan','White']), tags: ['beach','sea','pastel'] },
  { id: 'coastal_rocks', name: 'Coastal Rocks', indices: indicesByNames(['Dark Stone','Stone','Light Stone','Light Blue','Light Cyan']), tags: ['beach','earth','cool'] },
  { id: 'cave_paint', name: 'Cave Paint', indices: indicesByNames(['Deep Red','Dark Red','Dark Brown','Brown','Beige']), tags: ['earth','vintage','warm'] },
  { id: 'mocha_mint', name: 'Mocha Mint', indices: indicesByNames(['Dark Brown','Brown','Beige','Teal','Light Teal','White']), tags: ['contrast','earth','cool'] },
  { id: 'orchid', name: 'Orchid', indices: indicesByNames(['Dark Purple','Purple','Light Purple','Pink','Light Pink','White']), tags: ['purple','pastel'] },
  { id: 'peony', name: 'Peony', indices: indicesByNames(['Dark Pink','Pink','Light Pink','Peach','Light Peach','White']), tags: ['pastel','warm'] },
  { id: 'carnation', name: 'Carnation', indices: indicesByNames(['Pink','Light Pink','Light Purple','White','Light Yellow']), tags: ['pastel','bright'] },
  { id: 'sea_foam', name: 'Sea Foam', indices: indicesByNames(['Light Teal','Light Cyan','Light Blue','White']), tags: ['sea','pastel'] },
  { id: 'deep_forest', name: 'Deep Forest', indices: indicesByNames(['Black','Dark Olive','Dark Green','Dark Teal','Slate']), tags: ['forest','night','cool'] },
  { id: 'moss_and_bark', name: 'Moss & Bark', indices: indicesByNames(['Dark Olive','Olive','Light Olive','Dark Brown','Brown','Beige']), tags: ['forest','earth'] },
  { id: 'pine_snow', name: 'Pine & Snow', indices: indicesByNames(['Dark Green','Green','Light Green','Light Gray','White']), tags: ['forest','winter'] },
  { id: 'pumpkin_patch', name: 'Pumpkin Patch', indices: indicesByNames(['Dark Orange','Orange','Gold','Brown','Light Brown']), tags: ['autumn','season','earth'] },
  { id: 'marble', name: 'Marble', indices: indicesByNames(['White','Light Gray','Gray','Light Stone','Stone']), tags: ['neutral','luxury'] },
  { id: 'slate_rose', name: 'Slate Rose', indices: indicesByNames(['Slate','Light Slate','Pink','Light Pink','White']), tags: ['aesthetic','neutral'] },
  { id: 'hibiscus', name: 'Hibiscus', indices: indicesByNames(['Dark Pink','Pink','Light Pink','Light Purple','Light Yellow']), tags: ['pastel','warm'] },
  { id: 'berry_mint', name: 'Berry & Mint', indices: indicesByNames(['Dark Pink','Pink','Light Pink','Light Teal','Light Cyan','White']), tags: ['aesthetic','pastel'] },
  { id: 'royal_night', name: 'Royal Night', indices: indicesByNames(['Black','Indigo','Purple','Gold','White']), tags: ['luxury','night','contrast'] },
  { id: 'steel_blue', name: 'Steel Blue', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Blue','Blue']), tags: ['neutral','cool'] },
  { id: 'brass', name: 'Brass', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Gold','Beige']), tags: ['earth','warm','luxury'] },
  { id: 'sage', name: 'Sage', indices: indicesByNames(['Light Olive','Light Green','Light Teal','Light Beige','White']), tags: ['pastel','nature'] },
  { id: 'teal_blush', name: 'Teal Blush', indices: indicesByNames(['Teal','Light Teal','Pink','Light Pink','White']), tags: ['aesthetic','contrast'] },
  { id: 'coral_mint', name: 'Coral Mint', indices: indicesByNames(['Pink','Light Pink','Light Teal','Light Cyan','White']), tags: ['aesthetic','pastel'] },
  { id: 'plum', name: 'Plum', indices: indicesByNames(['Dark Purple','Purple','Light Purple','Light Pink','White']), tags: ['purple','pastel'] },
  { id: 'sunlit_stone', name: 'Sunlit Stone', indices: indicesByNames(['Light Stone','Stone','Light Gray','Gold','Light Yellow','White']), tags: ['earth','neutral','warm'] },
  { id: 'mist_forest', name: 'Mist Forest', indices: indicesByNames(['Light Olive','Light Green','Light Cyan','Light Gray','White']), tags: ['forest','pastel','cool'] },
  { id: 'azure_sand', name: 'Azure Sand', indices: indicesByNames(['Beige','Light Beige','Light Yellow','Cyan','Light Blue','White']), tags: ['beach','sea','bright'] },
  { id: 'granite', name: 'Granite', indices: indicesByNames(['Dark Stone','Stone','Light Stone','Gray','Light Gray','White']), tags: ['neutral','earth'] },
  { id: 'polar_night', name: 'Polar Night', indices: indicesByNames(['Black','Dark Slate','Dark Blue','Light Cyan','White']), tags: ['night','ice','contrast'] },
  { id: 'teal_rose', name: 'Teal Rose', indices: indicesByNames(['Teal','Light Teal','Pink','Light Pink','Light Yellow']), tags: ['aesthetic','pastel'] },
  { id: 'outrun_drive', name: 'Outrun Drive', indices: indicesByNames(['Black','Purple','Pink','Light Pink','Indigo','Light Blue','White']), tags: ['outrun','neon','night','aesthetic'] },
  { id: 'neon_grid', name: 'Neon Grid', indices: indicesByNames(['Black','Indigo','Cyan','Light Cyan','Pink','White']), tags: ['neon','night','aesthetic'] },
  { id: 'sunset_city', name: 'Sunset City', indices: indicesByNames(['Dark Blue','Indigo','Purple','Pink','Orange','Gold','Light Yellow']), tags: ['city','sunset','warm','cool'] },
  { id: 'night_market', name: 'Night Market', indices: indicesByNames(['Black','Dark Blue','Purple','Pink','Gold','Light Yellow']), tags: ['city','night','neon'] },
  { id: 'digital_rain', name: 'Digital Rain', indices: indicesByNames(['Black','Dark Blue','Blue','Cyan','Light Cyan']), tags: ['city','neon','cool','night'] },
  { id: 'hologram', name: 'Hologram', indices: indicesByNames(['Black','Indigo','Light Indigo','Cyan','Light Cyan','White']), tags: ['aesthetic','neon','cool'] },
  { id: 'laser_purple', name: 'Laser Purple', indices: indicesByNames(['Black','Dark Purple','Purple','Light Purple','Pink','White']), tags: ['neon','night','purple'] },
  { id: 'arcade', name: 'Arcade', indices: indicesByNames(['Black','Red','Green','Blue','Cyan','Yellow','White']), tags: ['retro','bright','neon'] },
  { id: 'neon_ocean', name: 'Neon Ocean', indices: indicesByNames(['Black','Teal','Cyan','Light Cyan','Purple','Pink']), tags: ['neon','sea','night'] },
  { id: 'cold_morning', name: 'Cold Morning', indices: indicesByNames(['Light Slate','Light Blue','Light Cyan','Light Gray','White']), tags: ['sky','cool','pastel'] },
  { id: 'evening_glow2', name: 'Evening Glow', indices: indicesByNames(['Dark Blue','Indigo','Light Indigo','Gold','Light Yellow']), tags: ['sky','night','contrast'] },
  { id: 'asphalt_heat', name: 'Asphalt Heat', indices: indicesByNames(['Dark Gray','Gray','Light Gray','Orange','Gold']), tags: ['city','warm','contrast'] },
  { id: 'metro_signs2', name: 'Metro Signs', indices: indicesByNames(['Black','Slate','Light Slate','Cyan','Yellow','White']), tags: ['city','bright'] },
  { id: 'industrial_rust2', name: 'Industrial Rust', indices: indicesByNames(['Dark Slate','Slate','Dark Red','Dark Orange','Goldenrod','Gray']), tags: ['city','vintage','earth'] },
  { id: 'warehouse', name: 'Warehouse', indices: indicesByNames(['Dark Gray','Gray','Light Gray','Brown','Beige','Light Beige']), tags: ['city','neutral','earth'] },
  { id: 'underground', name: 'Underground', indices: indicesByNames(['Black','Dark Slate','Slate','Indigo','Light Indigo']), tags: ['city','night','cool'] },
  { id: 'midnight_reef', name: 'Midnight Reef', indices: indicesByNames(['Black','Dark Blue','Teal','Cyan','Light Cyan']), tags: ['sea','night','cool'] },
  { id: 'taiga', name: 'Taiga', indices: indicesByNames(['Black','Dark Green','Green','Dark Olive','Slate']), tags: ['forest','cool','night'] },
  { id: 'wetland', name: 'Wetland', indices: indicesByNames(['Dark Olive','Olive','Light Olive','Teal','Light Teal']), tags: ['forest','nature','cool'] },
  { id: 'autumn_woods2', name: 'Autumn Woods', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Brown','Beige','Light Beige']), tags: ['forest','autumn','earth'] },
  { id: 'spring_greenery2', name: 'Spring Greenery', indices: indicesByNames(['Light Green','Green','Light Olive','Light Yellow','White']), tags: ['forest','spring','pastel'] },
  { id: 'red_desert', name: 'Red Desert', indices: indicesByNames(['Dark Red','Red','Dark Orange','Orange','Gold','Beige']), tags: ['desert','warm','earth'] },
  { id: 'dust_storm', name: 'Dust Storm', indices: indicesByNames(['Dark Beige','Beige','Light Beige','Light Yellow','Light Gray','White']), tags: ['desert','neutral','pastel'] },
  { id: 'salt_flats', name: 'Salt Flats', indices: indicesByNames(['White','Light Gray','Light Stone','Light Slate']), tags: ['desert','neutral'] },
  { id: 'ocher_dunes', name: 'Ocher Dunes', indices: indicesByNames(['Dark Beige','Beige','Light Beige','Goldenrod','Light Goldenrod']), tags: ['desert','earth','warm'] },
  { id: 'gunmetal', name: 'Gunmetal', indices: indicesByNames(['Black','Dark Gray','Gray','Dark Slate','Slate','Light Slate']), tags: ['neutral','city','mono'] },
  { id: 'brushed_steel', name: 'Brushed Steel', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Gray','Light Gray','White']), tags: ['neutral','cool'] },
  { id: 'oxidized_copper', name: 'Oxidized Copper', indices: indicesByNames(['Dark Brown','Brown','Goldenrod','Teal','Light Teal']), tags: ['vintage','earth','contrast'] },
  { id: 'patina', name: 'Patina', indices: indicesByNames(['Dark Brown','Brown','Beige','Teal','Light Teal','Light Cyan']), tags: ['vintage','earth','cool'] },
  { id: 'iron_ore', name: 'Iron Ore', indices: indicesByNames(['Black','Dark Gray','Gray','Dark Red','Brown']), tags: ['earth','neutral','industrial'] },
  { id: 'concrete_warm', name: 'Concrete Warm', indices: indicesByNames(['Stone','Light Stone','Beige','Light Beige','Light Gray']), tags: ['neutral','earth','warm'] },
  { id: 'porcelain', name: 'Porcelain', indices: indicesByNames(['White','Light Gray','Light Beige','Light Slate','Light Blue']), tags: ['neutral','pastel'] },
  { id: 'sandstone_blush', name: 'Sandstone Blush', indices: indicesByNames(['Light Stone','Stone','Light Beige','Light Peach','Light Pink']), tags: ['earth','pastel','warm'] },
  { id: 'grapefruit', name: 'Grapefruit', indices: indicesByNames(['Red','Orange','Yellow','Light Yellow','White']), tags: ['fruit','warm','bright'] },
  { id: 'peach_mint', name: 'Peach Mint', indices: indicesByNames(['Peach','Light Peach','Light Yellow','Light Teal','White']), tags: ['pastel','bright','aesthetic'] },
  { id: 'berry_mocha', name: 'Berry Mocha', indices: indicesByNames(['Dark Pink','Pink','Brown','Beige','White']), tags: ['warm','vintage','contrast'] },
  { id: 'mint_lime', name: 'Mint Lime', indices: indicesByNames(['Light Teal','Light Green','Light Yellow','White']), tags: ['pastel','bright','cool'] },
  { id: 'tropical_fruit', name: 'Tropical Fruit', indices: indicesByNames(['Pink','Orange','Gold','Green','Cyan','White']), tags: ['bright','fruit','summer'] },
  { id: 'lilac_bloom', name: 'Lilac Bloom', indices: indicesByNames(['Light Purple','Purple','Pink','Light Pink','White']), tags: ['pastel','purple'] },
  { id: 'violet_rose', name: 'Violet Rose', indices: indicesByNames(['Dark Purple','Purple','Pink','Light Pink','Gold']), tags: ['purple','aesthetic','warm'] },
  { id: 'sunflower', name: 'Sunflower', indices: indicesByNames(['Dark Goldenrod','Goldenrod','Light Goldenrod','Yellow','Light Yellow']), tags: ['warm','earth','season'] },
  { id: 'orchid_neon', name: 'Orchid Neon', indices: indicesByNames(['Black','Purple','Light Purple','Pink','Light Pink','White']), tags: ['neon','night','aesthetic'] },
  { id: 'duo_garnet_gold', name: 'Duo Garnet–Gold', indices: indicesByNames(['Black','Deep Red','Dark Red','Gold','White']), tags: ['duo','contrast','luxury'] },
  { id: 'duo_teal_magenta', name: 'Duo Teal–Magenta', indices: indicesByNames(['Black','Teal','Light Teal','Dark Pink','Pink','White']), tags: ['duo','contrast','neon'] },
  { id: 'duo_rose_cyan', name: 'Duo Rose–Cyan', indices: indicesByNames(['Black','Pink','Light Pink','Cyan','Light Cyan','White']), tags: ['duo','contrast','bright'] },
  { id: 'duo_olive_violet', name: 'Duo Olive–Violet', indices: indicesByNames(['Black','Olive','Light Olive','Purple','Light Purple','White']), tags: ['duo','contrast','aesthetic'] },
  { id: 'triad_primary', name: 'Triad Primary', indices: indicesByNames(['Red','Yellow','Blue','White']), tags: ['triad','classic','bright'] },
  { id: 'triad_green_purple_orange', name: 'Triad G–P–O', indices: indicesByNames(['Green','Purple','Orange','White']), tags: ['triad','contrast'] },
  { id: 'triad_teal_pink_gold', name: 'Triad Teal–Pink–Gold', indices: indicesByNames(['Teal','Pink','Gold','White']), tags: ['triad','aesthetic','contrast'] },
  { id: 'analog_blue_indigo_purple', name: 'Analog Blue–Indigo–Purple', indices: indicesByNames(['Blue','Light Blue','Indigo','Light Indigo','Purple']), tags: ['analogous','cool'] },
  { id: 'analog_green_teal_cyan', name: 'Analog Green–Teal–Cyan', indices: indicesByNames(['Dark Green','Green','Teal','Cyan','Light Cyan']), tags: ['analogous','cool'] },
  { id: 'noir_copper', name: 'Noir Copper', indices: indicesByNames(['Black','Gray','White','Dark Orange','Goldenrod']), tags: ['noir','contrast','vintage'] },
  { id: 'noir_teal', name: 'Noir Teal', indices: indicesByNames(['Black','Gray','White','Teal','Light Teal']), tags: ['noir','contrast','cool'] },
  { id: 'noir_gold2', name: 'Noir Gold 2', indices: indicesByNames(['Black','Gray','White','Gold','Yellow']), tags: ['noir','contrast','luxury'] },
  { id: 'pastel_blush', name: 'Pastel Blush', indices: indicesByNames(['Light Pink','Light Peach','Light Yellow','White']), tags: ['pastel','warm','bright'] },
  { id: 'pastel_sky2', name: 'Pastel Sky', indices: indicesByNames(['Light Blue','Light Indigo','Light Cyan','White']), tags: ['pastel','cool','sky'] },
  { id: 'pastel_mint_cream', name: 'Pastel Mint Cream', indices: indicesByNames(['Light Teal','Light Green','Light Yellow','Light Beige','White']), tags: ['pastel','nature'] },
  { id: 'pastel_lilac', name: 'Pastel Lilac', indices: indicesByNames(['Light Purple','Light Indigo','White']), tags: ['pastel','purple'] },
  { id: 'icy_dawn', name: 'Icy Dawn', indices: indicesByNames(['Light Blue','Light Cyan','Light Indigo','White','Light Yellow']), tags: ['ice','sky','pastel'] },
  { id: 'warm_noon', name: 'Warm Noon', indices: indicesByNames(['Gold','Yellow','Light Yellow','Beige','White']), tags: ['warm','bright'] },
  { id: 'cool_twilight', name: 'Cool Twilight', indices: indicesByNames(['Dark Blue','Blue','Light Indigo','Light Slate','White']), tags: ['sky','cool'] },
  { id: 'winter_evergreen', name: 'Winter Evergreen', indices: indicesByNames(['Dark Green','Green','Light Green','Light Slate','White']), tags: ['winter','forest','cool'] },
  { id: 'sunny_beach', name: 'Sunny Beach', indices: indicesByNames(['Light Beige','Light Yellow','Light Blue','Light Cyan','White']), tags: ['beach','bright','pastel'] },
  { id: 'stormy_beach', name: 'Stormy Beach', indices: indicesByNames(['Slate','Light Slate','Light Blue','Gold','Light Yellow']), tags: ['beach','contrast'] },
  { id: 'coral_sands', name: 'Coral Sands', indices: indicesByNames(['Pink','Light Pink','Light Beige','Light Yellow','White']), tags: ['beach','pastel','warm'] },
  { id: 'jade_sunset', name: 'Jade Sunset', indices: indicesByNames(['Teal','Light Teal','Gold','Orange','Light Yellow']), tags: ['contrast','warm','cool'] },
  { id: 'amber_indigo', name: 'Amber Indigo', indices: indicesByNames(['Dark Indigo','Indigo','Light Indigo','Gold','Light Yellow','White']), tags: ['contrast','luxury','night'] },
  { id: 'sapphire_gold', name: 'Sapphire & Gold', indices: indicesByNames(['Dark Blue','Blue','Light Blue','Gold','White']), tags: ['luxury','contrast'] },
  { id: 'emerald_gold', name: 'Emerald & Gold', indices: indicesByNames(['Dark Green','Green','Light Green','Gold','White']), tags: ['luxury','contrast','nature'] },
  { id: 'rose_gold', name: 'Rose Gold', indices: indicesByNames(['Pink','Light Pink','Gold','Light Yellow','White']), tags: ['luxury','aesthetic','warm'] },
  { id: 'pearl_blue', name: 'Pearl Blue', indices: indicesByNames(['White','Light Gray','Light Blue','Light Cyan','Light Indigo']), tags: ['neutral','pastel','cool'] },
  { id: 'steel_copper', name: 'Steel & Copper', indices: indicesByNames(['Dark Slate','Slate','Gray','Dark Orange','Goldenrod']), tags: ['contrast','industrial','vintage'] },
  { id: 'dawn_forest', name: 'Dawn Forest', indices: indicesByNames(['Light Yellow','Light Green','Green','Olive','Light Olive']), tags: ['forest','warm','nature'] },
  { id: 'evening_tundra', name: 'Evening Tundra', indices: indicesByNames(['Dark Slate','Slate','Light Slate','Dark Green','Light Green','White']), tags: ['nature','cool','neutral'] },
  { id: 'night_glow', name: 'Night Glow', indices: indicesByNames(['Black','Dark Blue','Indigo','Light Yellow','White']), tags: ['night','contrast'] },
].map(p => ({ ...p, indices: Array.from(new Set(p.indices)).sort((a,b)=>a-b) }));
